version: "3.9"

services:
  postgres:
    image: postgres:16

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: alzheimer_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .

    ports:
      - "8000:8000"

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/alzheimer_db

volumes:
  postgres_data: